"""Initial migration

Revision ID: fe686589d4eb
Revises: 
Create Date: 2025-11-01 01:08:28.803902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe686589d4eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_sessions_expires_at'), 'api_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_sessions_is_active'), 'api_sessions', ['is_active'], unique=False)
    op.create_index('ix_sessions_expires_active', 'api_sessions', ['expires_at', 'is_active'], unique=False)
    op.create_index('ix_sessions_token_active_expires', 'api_sessions', ['token_id', 'is_active', 'expires_at'], unique=False)
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'msg_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'msg_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('ix_sessions_token_active_expires', table_name='api_sessions')
    op.drop_index('ix_sessions_expires_active', table_name='api_sessions')
    op.drop_index(op.f('ix_api_sessions_is_active'), table_name='api_sessions')
    op.drop_index(op.f('ix_api_sessions_expires_at'), table_name='api_sessions')
    # ### end Alembic commands ###
