# Database Backup Automation Setup (Windows Task Scheduler)
#
# This script configures a Windows Task Scheduler job to run daily database backups at 2 AM.
#
# Usage (Run as Administrator):
#   powershell -ExecutionPolicy Bypass -File scripts\setup_backup_windows.ps1
#

# Requires Administrator privileges
#Requires -RunAsAdministrator

Write-Host "========================================" -ForegroundColor Green
Write-Host "Database Backup Automation Setup (Windows)" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir

# Check if backup script exists
$BackupScript = Join-Path $ScriptDir "backup_database.py"
if (-not (Test-Path $BackupScript)) {
    Write-Host "Error: Backup script not found at $BackupScript" -ForegroundColor Red
    exit 1
}

Write-Host "[1/5] Checking Python installation..." -ForegroundColor Green
$PythonCmd = Get-Command python -ErrorAction SilentlyContinue
if (-not $PythonCmd) {
    Write-Host "Error: Python is not installed or not in PATH" -ForegroundColor Red
    exit 1
}
$PythonVersion = python --version
Write-Host "  ✅ Python found: $PythonVersion" -ForegroundColor White

Write-Host ""
Write-Host "[2/5] Checking .env file..." -ForegroundColor Green
$EnvFile = Join-Path $ProjectDir ".env"
if (Test-Path $EnvFile) {
    Write-Host "  ✅ .env file found" -ForegroundColor White
} else {
    Write-Host "  ⚠️  .env file not found" -ForegroundColor Yellow
    Write-Host "  Make sure DATABASE_URL is configured" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "[3/5] Creating backup directory..." -ForegroundColor Green
$BackupDir = Join-Path $ProjectDir "backups"
New-Item -ItemType Directory -Force -Path (Join-Path $BackupDir "daily") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BackupDir "weekly") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $BackupDir "monthly") | Out-Null
Write-Host "  ✅ Backup directory: $BackupDir" -ForegroundColor White

Write-Host ""
Write-Host "[4/5] Creating backup wrapper script..." -ForegroundColor Green
# Create a batch file wrapper to load environment and run backup
$WrapperScript = Join-Path $ScriptDir "run_backup.bat"
$WrapperContent = @"
@echo off
REM Automated Backup Script Wrapper
REM Generated by setup_backup_windows.ps1

cd /d $ProjectDir

REM Load .env file if it exists
if exist .env (
    for /f "tokens=*" %%a in ('type .env') do (
        set %%a
    )
)

REM Run backup script
python "$BackupScript" --backup-dir "$BackupDir" >> logs\backup.log 2>&1

exit /b %ERRORLEVEL%
"@
Set-Content -Path $WrapperScript -Value $WrapperContent
Write-Host "  ✅ Wrapper script created: $WrapperScript" -ForegroundColor White

Write-Host ""
Write-Host "[5/5] Setting up Task Scheduler job..." -ForegroundColor Green

# Task parameters
$TaskName = "PiyasaChatBot-DatabaseBackup"
$TaskDescription = "Daily database backup for Piyasa Chat Bot at 2:00 AM"

# Check if task already exists
$ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($ExistingTask) {
    Write-Host "  ⚠️  Task already exists: $TaskName" -ForegroundColor Yellow
    $Overwrite = Read-Host "  Do you want to overwrite it? (y/n)"
    if ($Overwrite -ne "y" -and $Overwrite -ne "Y") {
        Write-Host "  Skipping task creation" -ForegroundColor Yellow
        exit 0
    }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "  Removed existing task" -ForegroundColor White
}

# Create action
$Action = New-ScheduledTaskAction `
    -Execute "cmd.exe" `
    -Argument "/c `"$WrapperScript`"" `
    -WorkingDirectory $ProjectDir

# Create trigger (Daily at 2:00 AM)
$Trigger = New-ScheduledTaskTrigger -Daily -At 2:00AM

# Create settings
$Settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable:$false `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries

# Create principal (run as current user)
$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType S4U `
    -RunLevel Limited

# Register task
Register-ScheduledTask `
    -TaskName $TaskName `
    -Description $TaskDescription `
    -Action $Action `
    -Trigger $Trigger `
    -Settings $Settings `
    -Principal $Principal | Out-Null

Write-Host "  ✅ Task Scheduler job created successfully" -ForegroundColor White

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Backup schedule:" -ForegroundColor White
Write-Host "  • Daily:   2:00 AM (keep last 7 days)" -ForegroundColor White
Write-Host "  • Weekly:  2:00 AM on Sundays (keep last 4 weeks)" -ForegroundColor White
Write-Host "  • Monthly: 2:00 AM on 1st of month (keep last 12 months)" -ForegroundColor White
Write-Host ""
Write-Host "Backup location:" -ForegroundColor White
Write-Host "  $BackupDir" -ForegroundColor Cyan
Write-Host ""
Write-Host "Log file:" -ForegroundColor White
Write-Host "  $ProjectDir\logs\backup.log" -ForegroundColor Cyan
Write-Host ""
Write-Host "Manual backup:" -ForegroundColor White
Write-Host "  python $BackupScript" -ForegroundColor Cyan
Write-Host ""
Write-Host "View scheduled tasks:" -ForegroundColor White
Write-Host "  Get-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Cyan
Write-Host ""
Write-Host "Run task manually:" -ForegroundColor White
Write-Host "  Start-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Cyan
Write-Host ""
Write-Host "Remove task:" -ForegroundColor White
Write-Host "  Unregister-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Cyan
Write-Host ""
